In [ ]:
import numpy as np
from find_examples import CorpusExamples
import multiprocess as mp

corpus_folder = "/media/ducha/SSDSHARED/VN/subs_dump/viet_subs_processed2"
corpus = CorpusExamples(corpus_folder)
csv_path = "/home/ducha/Dropbox/Tiếng Việt/Ngữ Vựng/1000.csv"

with open(csv_path, "r") as f:
    csv_1k = [line.strip().split(";") for line in f]

Preparing corpus from /media/ducha/SSDSHARED/VN/subs_dump/viet_subs_processed2
Corpus prepared with 13646 files
Total Examples 7736833


In [ ]:
import seaborn as sns

ex = csv_1k[0][0]
ex
found_exs = corpus.find_examples(ex)

lens = [e["num_words"] for e in found_exs]

np.mean(lens), np.std(lens), np.median(lens), np.max(lens), np.min(lens), len(lens)

sns.displot(lens, bins=range(min(lens), max(lens) + 1))

'hình dạng'

In [28]:
[e["text"] for e in found_exs if e["num_words"] == 10]

['Những con quỷ mạnh có thể biến đổi hình dạng.',
 'Hãy nhìn vết máu bắn, xem hình dạng của chúng.',
 'Kích cỡ và hình dạng lý tưởng cho khoái cảm.',
 'Ta nhận ra ngươi rồi, hình dạng thật của ngươi!',
 'Tớ quên là cậu đã đổi hình dạng Hermione đâu?',
 'Hoá ra đây là hình dạng thật sự của ngươi.',
 'Các gia đình có đủ hình dạng và kích cỡ.',
 'Người đã tạo ra tôi theo hình dạng Xin chào.',
 'Nhìn khớp mu và hình dạng của trám bịt đi.',
 'Chúng là những con quỷ trong hình dạng con người.',
 'Hình dạng của các tàu bay này rất đa dạng.',
 'Cho nên mới trở thành hình dạng như hiện nay.',
 'Tối qua, tôi đi ngủ dưới hình dạng của tôi.',
 'Chẳng phải ngươi là kẻ thay đổi hình dạng sao?',
 'Hay là đệ biến thành hình dạng của sư phụ.',
 'Sau khi thấy hình dạng thật của tôi Gì hả?',
 'Và sâu bên dưới ...với hình dạng to lớn này',
 '...thành hình dạng, con số, và âm thanh nào đó.',
 '- Tôi ghét hình dạng của bàn chân của bạn!',
 'Vẫn là chất đó, chỉ có hình dạng thay đổi.',
 'Một, công lý có đủ m

# Filling

From the earlier analysis, the bounds (8, 14) seems reasonable. Thus we can try to sample from that distribution. To sample we can:

1. Find all the examples first
2. sort the examples by length in a dict
3. sample 5 from the length distribution and samle randomly form the grouped sentences

In [67]:
import numpy as np

lens_distribution = np.load("example_distribution.npy")  # Shape: (X, p)
lens_distribution

array([[ 8.        ,  0.18421052],
       [ 9.        ,  0.20394737],
       [10.        ,  0.17105263],
       [11.        ,  0.1513158 ],
       [12.        ,  0.15789473],
       [13.        ,  0.08552632],
       [14.        ,  0.04605263]], dtype=float32)

In [26]:
import numpy as np
from find_examples import CorpusExamples
import multiprocess as mp

corpus_folder = "/media/ducha/SSDSHARED/VN/subs_dump/viet_subs_processed2"
corpus = CorpusExamples(corpus_folder)

Preparing corpus from /media/ducha/SSDSHARED/VN/subs_dump/viet_subs_processed2
Corpus prepared with 13646 files
Total Examples 7736833


In [68]:
found_examples = corpus.find_examples("hình dạng")

In [69]:
# Dict that groups by `num_words`
grouped = {}
for e in found_examples:
    num_words = e["num_words"]
    if num_words not in grouped:
        grouped[num_words] = []
    grouped[num_words].append(e["text"])

In [76]:
n_examples = 5
samples = np.random.choice(
    lens_distribution[:, 0], n_examples, p=lens_distribution[:, 1]
)

# Count the entries in samples
samples = np.vstack(np.unique(samples, return_counts=True)).astype(int).T

In [78]:
samples

array([[10,  2],
       [12,  2],
       [13,  1]])

In [79]:
result = []
for i in range(len(samples)):
    sampled_len, n = samples[i, 0], samples[i, 1]
    print(f"Sampling len {sampled_len} {n} times")
    examples_with_len = grouped[sampled_len]
    sampled_examples = np.random.choice(examples_with_len, n, replace=False)
    result.extend(sampled_examples)

Sampling len 10 2 times
Sampling len 12 2 times
Sampling len 13 1 times


In [80]:
result

['Hình dạng của các tàu bay này rất đa dạng.',
 'Ta nhận ra ngươi rồi, hình dạng thật của ngươi!',
 'thực thể sẽ tồn tại không hình dạng Rất có khả năng,',
 'Đã lâu không gặp, sao lại biến thành hình dạng như vậy?',
 'Dựa trên hình dạng cái xác, anh ta đã chết hơn một tuần.']

# Going Over all Words

In [6]:
import numpy as np
from find_examples import CorpusExamples
import multiprocess as mp

corpus_folder = "/media/ducha/SSDSHARED/VN/subs_dump/viet_subs_processed2"
corpus = CorpusExamples(corpus_folder)

lens_distribution = np.load("example_distribution.npy")  # Shape: (X, p)
lens_distribution

Preparing corpus from /media/ducha/SSDSHARED/VN/subs_dump/viet_subs_processed2
Corpus prepared with 13646 files
Total Examples 7736833


array([[ 8.        ,  0.18421052],
       [ 9.        ,  0.20394737],
       [10.        ,  0.17105263],
       [11.        ,  0.1513158 ],
       [12.        ,  0.15789473],
       [13.        ,  0.08552632],
       [14.        ,  0.04605263]], dtype=float32)

In [7]:
csv_path = "/home/ducha/Dropbox/Tiếng Việt/Ngữ Vựng/1000.csv"

with open(csv_path, "r") as f:
    csv_1k = [line.strip().split(";") for line in f]

In [8]:
from tqdm.notebook import tqdm

csv_path_filled = "/home/ducha/Dropbox/Tiếng Việt/Ngữ Vựng/1000_filled.csv"
ex_separator = "|"
n_examples = 5

In [10]:
for entry in tqdm(csv_1k):
    if len(entry) != 3:
        continue
    vi, en, _ = entry

    found_exs = corpus.find_examples(vi)
    if len(found_exs) == 0:
        continue

    if len(found_exs) < n_examples:
        print("Not sampling, as there are too few examples.")
        entry[2] = ex_separator.join([e["text"] for e in found_exs])
    else:
        # Dict that groups by `num_words`
        grouped = {}
        for e in found_exs:
            num_words = e["num_words"]
            if num_words not in grouped:
                grouped[num_words] = []
            grouped[num_words].append(e["text"])

        n_examples = 5
        samples = np.random.choice(
            lens_distribution[:, 0], n_examples, p=lens_distribution[:, 1]
        )
        print(f"Sampling from {len(found_exs)} examples: {samples}")
        # Count the entries in samples
        samples = np.vstack(np.unique(samples, return_counts=True)).astype(int).T

        result = []
        for i in range(len(samples)):
            sampled_len, n = samples[i, 0], samples[i, 1]
            examples_with_len = grouped[sampled_len]
            sampled_examples = np.random.choice(examples_with_len, n, replace=False)
            result.extend(sampled_examples)

        entry[2] = ex_separator.join(result)

  0%|          | 0/1000 [00:00<?, ?it/s]

Sampling from 320 examples: [ 9. 14. 10. 11.  9.]
Sampling from 261 examples: [ 8. 11. 10. 12. 11.]
Sampling from 9046 examples: [10.  9. 11.  8. 12.]
Sampling from 1260 examples: [14. 11. 11. 11. 12.]
Sampling from 1099 examples: [10. 14. 12. 10. 10.]


KeyboardInterrupt: 

In [11]:
csv_1k[:10]

[['hình dạng',
  'shape',
  'Tạo ra rất nhiều hình dạng, và mọi thứ.|Phải chăng đây là hình dạng gốc của nó?|Tớ quên là cậu đã đổi hình dạng Hermione đâu?|Họ hay nói nó có hình dạng Đúng, tôi nhớ rồi.|Không thể đi Ye Qiu Da Shen chuyển sang hình dạng của chiếc ô'],
 ['phẳng',
  'flat',
  'Hăy nhìn vào cái màn hình phẳng kia.|Dù "chỗ đó" của họ "bằng phẳng" đi chăng nữa.|với một kết thúc phẳng lì và Bình tĩnh đi, Dermot.|Ngồi đến phẳng mông mà chẳng mua được mẩu bánh mì!|Bằng phẳng như thế này thật sự là rất thông minh đấy.'],
 ['công việc',
  'work',
  'Chị cần nói chuyện công việc với bố.|Công việc hoặc thí nghiệm hồi xưa chẳng hạn.|mà tôi không nhớ gì về công việc trước đây.|Tôi nghe nói rằng công việc đang trở lên khó khăn.|Có điều chúng tôi biết là trong đó có một công việc.'],
 ['kinh nghiệm',
  'experience',
  'Em không có kinh nghiệm Em không học ở Harvard à?|Tớ không có tí kinh nghiệm nào, nhưng... Cảm ơn cậu.|Đội judo cậu gặp lần trước đều có kinh nghiệm cả.|Không, không phải 

In [ ]:
with open(csv_path_filled, "w") as f:
    for entry in csv_1k:
        f.write(";".join(entry) + "\n")

# Semantic Similarity

In [2]:
import numpy as np
from find_examples import CorpusExamples
import multiprocess as mp

corpus_folder = "/media/ducha/SSDSHARED/VN/subs_dump/viet_subs_processed2"
corpus = CorpusExamples(corpus_folder)
csv_path = "/home/ducha/Dropbox/Tiếng Việt/Ngữ Vựng/1000.csv"

with open(csv_path, "r") as f:
    csv_1k = [line.strip().split(";") for line in f]

Preparing corpus from /media/ducha/SSDSHARED/VN/subs_dump/viet_subs_processed2
Corpus prepared with 13646 files
Total Examples 7736833
Using semantic sorting.


In [6]:
from tqdm.notebook import tqdm

for entry in tqdm(csv_1k):
    vi, en, exs = entry
    found_exs = corpus.find_examples(vi)[:5]
    if len(found_exs) == 0:
        continue
    entry[2] = "|".join([e["text"] for e in found_exs])

  0%|          | 0/1000 [00:00<?, ?it/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The 

KeyboardInterrupt: 

In [5]:
csv_1k[0]

['hình dạng',
 'shape',
 'trong hình dạng một con vật|Hình dạng nó thế nào?|Chúng có hình dạng thế nào?|Các màu sắc và hình dạng,|Dù là hình dạng gì.']